### PR TITLE
Fix more breakage similar to rust-lang/rust#36340 and 11f118643

### LINKED ISSUE #222: "error: the type of this value must be known in this context" for `as_ref`
With:

```
$ rustc --version 
rustc 1.15.0-nightly (03bdaade2 2016-11-27)
```

I get the following error:

```
error: the type of this value must be known in this context
   --> /home/emk/.cargo/registry/src/github.com-1ecc6299db9ec823/postgres-0.13.2/src/lib.rs:794:61
    |
794 |                 let get_raw = |i| row.get(i).and_then(|r| r.as_ref().map(|r| &**r));
    |                                                             ^^^^^^
```

This looks like it's related to 11f11864391ae457881a0377f89b154e897d094d and possibly rust-lang/rust#36340.

### PR DESCRIPTION
**Pull request by emk**
Fixes #222.

### CODE REVIEW

**Comment by emk** [comment]
The build failure on Travis CI is caused by the problem with SSL on Cargo nightlies, and can be fixed by either waiting for the next Cargo, or by adding `export SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt` to the build for a couple of days.

**Comment by sfackler** [comment]
Oops, though I already fixed this, thanks!

**Comment by sfackler** [comment]
Released 0.13.3

**Comment by emk** [comment]
@sfackler You fixed one of the places where this issue appeared but I found a second one. :-) Thank you for the fast turnaround!

**Pull request merged**
