### PR TITLE
Add handling of DB-Errors in Notification processing

### PR DESCRIPTION
**Pull request by dunkelstern**
Handle the error that is generated when the DB connection goes down instead of panicing with
an unreachable code error. This allows the notification client to retry establishing the
connection instead of crashing the complete program.

I am very new to rust so please advise if this looks wrong to you.

### CODE REVIEW

**Comment by sfackler** [comment]
Thanks! I'd like to add some tests to make sure this doesn't regress in the future, but I'm not sure of a great way to inject an error into a connection. Is there any way you can think of? We can merge as-is if not.

**Comment by sfackler** [comment]
Ah, `pg_terminate_backend()` might be able to do it: https://www.postgresql.org/docs/current/static/functions-admin.html

**Comment by dunkelstern** [comment]
I'll try to write a test, will push to this PR

**Comment by dunkelstern** [comment]
Test is committed, seems to run ok on the CI

**Comment by sfackler** [comment]
Thanks!

**Pull request merged**
