### PR TITLE
Macaddr

### PR DESCRIPTION
**Pull request by abaumhauer**
Here is my implementation of MACADDR handling using my crate eui48.  There are only minor changes to your code to support it.  Thanks for making it so easy to extend your crate for additional types.

### CODE REVIEW

**Comment by sfackler** [comment]
Can you tweak this line so that travis tests this feature? https://github.com/sfackler/rust-postgres/blob/master/.travis.yml#L13

Looks good other than that, thanks!

**Comment by abaumhauer** [comment]
Ok, change made.  Do I need to do another pull request, or is the
current one ok?
Andy

**Comment by sfackler** [comment]
Nope, should be fine in this PR. I forgot one more thing - could you add a test for this? You should be able to model it after the tests for other optional types like UUID: https://github.com/sfackler/rust-postgres/blob/master/tests/types/uuid.rs

**Comment by abaumhauer** [comment]
Added travis test to exercise parse_str() function as requested.

**Comment by sfackler** [comment]
Awesome, thanks!

**Pull request merged**
