### PR TITLE
One example, doing a `select 1;`

### PR DESCRIPTION
**Pull request by kosta**
Is this the intended usage?

Part of #390 

In #117 you said you wanted feedback on the new tokio API. Here it is:

* I was confused by `Connection` no longer having a `connect` method but the "free" `connect` method is quick to find, so that's ok I guess. Can be fixed by documentation if you want to keep this design.
* `connect` returning a Handshake which is a `Future<Item=(Connection, Client)>` is fine. However, what confused the heck out of me was that Connection is a `Future<Item=()>` and basically does nothing user-visible. `Client` does all the things (prepare, query, execute, ...). So first I tried ignoring `Connection` and just calling `Client.prepare()`, which yields a Connection closed error. Weird. Then I tried waiting for `Connection` to resolve `and_then` calling `Client.prepare()`, which block forever. Hm. Then I got the idea to maybe call `connection.join(client...)` and that worked! This is really not intuitive. I'm not deep enough into the architecture to have any say whether this makes sense internally, but at the very least, this needs good documentation. (Maybe the example in this PR is a start)

One word about performance: It rocks! 🥇 

I'm using this to validate some database experiments, and the single-threaded insert performance of tokio_postgres with "perpared statements without (explicit) transactions" is about 4 times that of "chunk 1000 inserts into one transaction" for my use case.  So I'm very happy :D

Let me know what you think, I'm happy to make any adjustments you propose.

### CODE REVIEW

**Comment by sfackler** [comment]
The more common approach is to simply spawn off the connection to run in the background: https://github.com/sfackler/rust-postgres/blob/master/tokio-postgres/tests/test.rs#L176

**Comment by kosta** [comment]
Makes sense! I will update the example accordingly.

**Comment by kosta** [comment]
I tried to update it to use `runtime.spawn(connection)`, but I see that you removed the `connect()` method. Is there still a way to parse a `postgres://` url to connect? I could only find using the Builder() struct.

Also, does this example make much sense? Should I instead to adopt the "Readme" example for tokio-postgres?

**Comment by kosta** [comment]
I tried to update it to use `runtime.spawn(connection)`, but I see that you removed the `connect()` method. Is there still a way to parse a `postgres://` url to connect? I could only find using the Builder() struct.

Also, does this example make much sense? Should I instead to adopt the "Readme" example for tokio-postgres?

**Comment by sfackler** [comment]
> Is there still a way to parse a `postgres://` url to connect?

Not currently - that's the next bit of functionality I'm planning on working on.

**Comment by kosta** [comment]
Hm, from skimming the commit messages I feel that writing examples _currently_ might be not the best idea while you're doing major rewrites. 

Is it ok to close this? 

Feel free to ping me (on this issue or #390) once the API is in a state where adding examples and documentation makes more sense...

**Comment by sfackler** [comment]
Yeah, I think there's probably enough churn right now that examples will be immediately out of date :)

I'll be sure to ping you when it starts to stabilize! I think we're pretty close. The remaining bits are mostly the conveniences around connecting.

**Comment by kosta** [comment]
Closing.

This example was bad anyway, I'll try to re-create the "person" example from current (non-tokio) release once this stabilizes.

**Pull request closed without merging**
