### PR TITLE
Fixes for bb8

### PR DESCRIPTION
**Pull request by khuey**
To write bb8 (https://github.com/khuey/bb8) I made a few modifications to tokio_postgres. These do change the exposed interface.

- `Handshake` no longer consumes itself. This wasn't necessary and allows a single `Handshake` to be shared among multiple connections.
- An `is_desynchronized` is added, mirroring the one in sync `postgres`.
- The `TlsMode` enum now holds references, like its equivalent in sync `postgres`. This requires bounding a couple futures to the lifetime of the `TlsMode`. I expect this to be the most controversial part. Since you can still shove your `Handshake` in a `lazy_static!` to get the static lifetime if you really need it I don't think this is a huge issue.

### CODE REVIEW

**Comment by sfackler** [comment]
You can't put a Handshake in a lazy_static if it needs any runtime-derived configuration. I think it may make more sense for bb8 to define a `trait MakeHandshake { fn make_handshake(&self) -> Box<Handshake>; }` instead?

**Comment by khuey** [comment]
If it needs runtime configuration other than environment variables or similar, sure. Do you know of examples of usage that I can look at?

**Comment by sfackler** [comment]
I don't know of any public examples offhand, but it's relatively common for an application to read a config file and initialize things based off of that at startup, including its connection pool.

**Comment by khuey** [comment]
Alright lets just drop those csets then.

**Comment by khuey** [comment]
Poke?

**Comment by khuey** [comment]
ty!

**Pull request merged**
