### PR TITLE
removed sealed trait

### PR DESCRIPTION
**Pull request by Bjohnson131**
implementation of https://github.com/sfackler/rust-postgres/issues/912

### CODE REVIEW

**Comment by sfackler** [comment]
Can you show me an example of an implementation of this trait you would make if this were merged?

**Comment by Bjohnson131** [comment]
Sure! give me a bit.

**Comment by Bjohnson131** [comment]
So here's the most basic implementation that I could come up with,  There are some changes that need to be made to the PR to get this to work properly. Name, that the members of a Row be made pub, but I'm sure there's other things I could add in.

```rs 

use postgres::{CopyInWriter, CopyOutReader, RowIter, Transaction};
use tokio_postgres::types::{BorrowToSql, ToSql, Type};
use tokio_postgres::{Error, Row, SimpleQueryMessage, Statement, ToStatement};

struct mock_client {
    should_error: bool,
    execute_result: u64,
    row_result: Row,
}

impl postgres::GenericClient for mock_client {
    fn execute<T>(&mut self, _query: &T, _params: &[&(dyn ToSql + Sync)]) -> Result<u64, Error>
    where
        T: ?Sized + ToStatement,
    {
        if self.should_error {
            return Err(Error::Error());
        }
        return Ok(self.execute_result);
    }

    fn query<T>(&mut self, _query: &T, _params: &[&(dyn ToSql + Sync)]) -> Result<Vec<Row>, Error>
    where
        T: ?Sized + ToStatement,
    {
        if self.should_error {
            return Err(Error::Error());
        }
        return Ok(vec![self.row_result]);
    }

    fn query_one<T>(&mut self, _query: &T, _params: &[&(dyn ToSql + Sync)]) -> Result<Row, Error>
    where
        T: ?Sized + ToStatement,
    {
        if self.should_error {
            return Err(Error::Error());
        }
        // Alternatively: self.row.clone()
        return Ok(Row {
            statement: self.row_result.statement.clone(),
            body: DataRowBody{
                self.row_result.body.storage.clone(),
                self.row_result.body.len.clone(),
            },
            ranges: self.row_result.ranges.clone(),
        });
    }
//[...]
}

```

and so on.


The idea is that since I'm writing unit tests to handle responses from the crate, you can craft those responses yourself as test-cases instead of having a live instance.  this way, we could make our functions use a 'GenericClient' instead of a postgres::client as a parameter, allowing us to pass in a 'mock_client' for our unit tests, and a postgres::client for live code.

**Comment by sfackler** [comment]
I don't think I would want to make types like Row publicly constructible. If you want to do this kind of unit testing, I would recommend creating your own trait hierarchy that would allow you to mock out all of those types together.

**Comment by Bjohnson131** [comment]
So one should make my own data type derived from a row, and mock that, if
I'm understanding correctly?

**Comment by sfackler** [comment]
You'd make a trait that you implement for Row and your own testing type.

**Comment by sfackler** [comment]
How are you going to construct the `Row` your trait implementation has to return?

**Comment by Bjohnson131** [comment]
I suppose there would need to be a change to tokio-postgres. Should I add that to the PR?

**Comment by sfackler** [comment]
What would that change be? If it's a breaking one that's not going to work until I get ready to cut the next major version bump.

**Comment by Bjohnson131** [comment]
give me a few weeks to get a solution that's a drop-in for the existing
code, and maybe some tests. feel free to assign me to the pr. I'll @ you
when I have something ready to review.. Marking as a draft for now.

**Pull request closed without merging**
