### PR TITLE
Include message object in UnexpectedMessage error

### PR DESCRIPTION
**Pull request by jeff-davis**
Make it easier to debug unexpected messages in the protocol flow.

### CODE REVIEW

**Comment by sfackler** [comment]
I'm a bit worried about large and/or sensitive messages getting stored in the error and propagated around. How about just storing the message tag? That should be enough for a developer to figure out which unexpected message came in without having those issues.

**Comment by jeff-davis** [comment]
Ideally, the `{:?}` of the message would be the enum variant name, but I don't see a simple way to add that kind of reflection without a macro.

I could add the macro, or if you don't tihnk it's worthwhile, I'm OK dropping this patch. My replication client code is working pretty well after I sorted out some under-specified areas of the protocol.

**Comment by sfackler** [comment]
An enum would work fine as well, I'd just prefer it to be a separate enum than the one that actually stores the data.

I personally just use Wireshark to see what's going on when I hit a protocol error.

**Comment by jeff-davis** [comment]
Yeah, it doesn't seem worth the trouble to fix this. Closing.

**Pull request closed without merging**
