### PR TITLE
Added crude BigRational ToSql FromSql for numeric

### PR DESCRIPTION
**Pull request by kvsari**
Please have a look at this code and let me know if it's acceptable.

### CODE REVIEW

**Comment by sfackler** [comment]
Could you add some tests to exercise these implementations?

**Comment by kvsari** [comment]
I want to have a random battery of tests but for that I need to import the rand crate I imagine.

**Comment by sfackler** [comment]
You'll need to adjust .travis.yml to add the new num feature.

**Comment by kvsari** [comment]
Cancelling pull request. I don't know what to do about 1/3.

**Comment by kvsari** [comment]
I've added some battery tests and set the 1/3 test to fail.

**Comment by sfackler** [comment]
I'm not sure that `BigRational` is the right type to match to `NUMERIC` due to the issues with e.g. 1/3. It seems like it really needs something like [BigDecimal](https://docs.oracle.com/javase/7/docs/api/java/math/BigDecimal.html).

**Comment by ELD** [comment]
It really does since BigDecimal allows you to specify the precision.

Adding a BigDecimal type to `num` is something I've been meaning to experiment with. I understand the concepts, I just need to sit down and try to write it out.

**Comment by kvsari** [comment]
Ok, I'll close this request until a BigDecimal is available.

**Pull request closed without merging**
