### PR TITLE
Add keywords to improve linkability on crates.io

### PR DESCRIPTION
**Pull request by kud1ing**
* https://crates.io/keywords/postgres
* https://crates.io/keywords/postgresql

### CODE REVIEW

**Comment by sfackler** [comment]
Weird, I thought the readme was indexed for search as well - is that not the case @alexcrichton?

**Comment by alexcrichton** [comment]
The readme is indexed, yeah, but it has a much lower search priority than the keywords, for example.

**Comment by kud1ing** [comment]
Thank you.

I think keyword links are more precise. If you search for "orm" you also get https://crates.io/crates/rustless/ which i would not consider an ORM.

**Comment by kud1ing** [comment]
My motivation is to add crates.io links to https://github.com/kud1ing/awesome-rust and i want them to be precise.

**Pull request merged**
