### PR TITLE
Add generic immutable interface.

### PR DESCRIPTION
**Pull request by enzious**
I added a GenericClient trait over Client and Transaction, and replaced &mut with & to support the same style of trait as in previous versions.

I'm using GenericConnection in the old versions and I just wanted to try to add it back. I just named it GenericClient to match the new Client struct.

Thoughts?

Related issue:
#329

### CODE REVIEW

**Comment by sfackler** [comment]
The methods should take `&mut self`.

**Comment by enzious** [comment]
Could you explain that? It wasn't like this in the previous versions. Is this because of tokio?

In the old version I was using Rc<Connection>, but with this I'll have to use Rc<RefCell<Client>> everywhere.

**Comment by sfackler** [comment]
Internal mutability is very rare in Rust APIs. It only existed in this library because of an old, pre-Rust 1.0 API design that was overhauled significantly in the latest release.

If you want to use internal mutability in your code, you can use a RefCell as you've noted, but a connection pool like r2d2 is possibly a more appropriate choice.

**Comment by enzious** [comment]
r2d2 uses an Arc which is little heavy for what I need.

**Comment by sfackler** [comment]
What percentage of your runtime has your profiling indicated is spent in Arc code?

**Comment by enzious** [comment]
It's a discord/twitch clone (weird I know), but if users are spamming I don't want a ton of Arc locks.

**Comment by sfackler** [comment]
That wasn't really an answer to my question.

**Comment by enzious** [comment]
I haven't profiled this app, but in a previous experience with Arcs it was pretty bad.

**Comment by sfackler** [comment]
Arcs are used in proximity to all kinds of high performance code (and an Arc is not a lock in the first place). I'm not interested in adding a bunch of internal mutability back to this crate.

**Comment by enzious** [comment]
What about a GenericClient trait?

**Comment by sfackler** [comment]
Sure, I'd be happy to add that trait back.

**Comment by enzious** [comment]
And you're right, I was thinking of Arc<Mutex<T>>

**Comment by colingm** [comment]
@sfackler did you ever look at bringing back the GenericConnection trait into the newer versions?

**Comment by sfackler** [comment]
Ah, I have not yet but it seems reasonable to do!

**Comment by colingm** [comment]
@sfackler was there a specific change or re-architecture that prompted its removal? Just wanting to make sure there wasn't a better way to handle that need that I was missing.

**Comment by sfackler** [comment]
The crate was rewritten from scratch, and the trait just never made it back in.

**Pull request closed without merging**
