### PR TITLE
document prepared statements should be used for user specified data

### PR DESCRIPTION
**Pull request by toidiu**
Wanted to add this note in the main Readme so its easier to find. From experience, this took a lot of searching.

### CODE REVIEW

**Comment by sfackler** [comment]
```rust
let updates = conn.execute("UPDATE foo SET bar = $1 WHERE baz = $2", &[&1i32, &"biz"])?;
```
is just as secure as
```rust
let stmt = conn.prepare("UPDATE foo SET bar = $1 WHERE baz = $2")?;
stmt.execute(&[&1i32, &"biz"])?;
```
but the added paragraph seems to imply that that's not the case.

**Comment by toidiu** [comment]
Ahh, I wasn't sure. Looking at the docs here https://docs.rs/postgres/0.16.0-rc.2/postgres/struct.Client.html#method.query, they only mention that simple_query is not safe. Does that mean all other operations, even `query` is safe?

**Comment by sfackler** [comment]
The unsafe thing is if you manually construct a query string containing user-provided data.

**Comment by toidiu** [comment]
So if I am understanding you correctly, `simple_query_*` are the only unsafe operations on the client.

That wasnt obvious to me from reading the docs/readme. I think it could be useful to mention that somewhere?

Do let me know if you agree and if the Readme or docs or both might be a good location to document that. Also thanks for the quick responses!

**Comment by sfackler** [comment]
`simple_query` and `batch_execute` are the only methods that have warnings about not using them with user-provided parameters: https://docs.rs/postgres/0.16.0-rc.2/postgres/struct.Client.html#warning

**Comment by toidiu** [comment]
got it, that seems sufficient then. thanks

**Pull request closed without merging**
