### PR TITLE
feat: support [u8; N] as BYTEA

### PR DESCRIPTION
**Pull request by xoac**
There is a implementation for `&[u8]` but lacking implementation of `[u8; N]` what this PR is try to add.
Waiting for feedback

### CODE REVIEW

**Comment by sfackler** [comment]
This already exists under the `array-impls` Cargo feature.

**Comment by xoac** [comment]
Could you show me where? There is general implementation for [T; N] but I don't see it could map to [u8; N].

Also if this would be implemented my PR should not compile.
Also my LSP provide `to_sql` method for `[0u32, 0]` but not for `[0u8, 0]`

**Comment by sfackler** [comment]
Oh sorry - I misread!

**Comment by sfackler** [comment]
Could you update the `ToSql` docs as well? LGTM otherwise.

**Comment by sfackler** [comment]
Thanks!

**Pull request merged**
