### PR TITLE
Implement  HashSet FromSql ToSql

### PR DESCRIPTION
**Pull request by kingxsp**

### CODE REVIEW

**Comment by sfackler** [comment]
I'm not sure I agree with this - sets are not the same thing as arrays.

**Comment by kingxsp** [comment]
Is there any way to store a HashSet?

**Comment by sfackler** [comment]
If you want to store the values as an array in postgres, you can convert to an array in Rust as well. Not sure if there's a native set type off the top of my head.

**Comment by kingxsp** [comment]
yes. but  I just want to make it easy.

**Pull request closed without merging**
